### ISSUE TITLE
How to filter data?

### ISSUE THREAD

**Issue by ahmedNY** [Dev-Owl/advanced_datatable#1]

**Comment by Dev-Owl** [comment]
Hi,

The idea of a server side control requires to apply filters on the server , alongside with the sorting. Have a look at the example code to see how data can be send to the server. Of course, this can be done in any way you like (HTTP Body, Websockets, Query string etc.).

The server side code is also public available including a little article.

[Article](https://link.medium.com/bvtZDeFbZhb)

[Code](https://github.com/Dev-Owl/dart_backend_example/tree/main/bin)

Once I get a bit of time I can include filter in the example as well, but it will be 100% related to your backend.
Hope this helps you, feel free to comment if you have further questions.

**Comment by ahmedNY** [comment]
This is is small example I made, would you help me to make this example work
`import 'package:advanced_datatable/advancedDataTableSource.dart';
import 'package:advanced_datatable/datatable.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

const data = [
  {"id": "1", "first_name": "britney", "last_name": "sims"},
  {"id": "2", "first_name": "imogen", "last_name": "edwards"},
  {"id": "3", "first_name": "lillian", "last_name": "simmmons"},
  {"id": "4", "first_name": "jessica", "last_name": "torres"},
  {"id": "5", "first_name": "noelia", "last_name": "suarez"},
  {"id": "6", "first_name": "susanna", "last_name": "mast"},
  {"id": "7", "first_name": "christa", "last_name": "lehmann"},
  {"id": "8", "first_name": "سورنا", "last_name": "رضایی"},
  {"id": "9", "first_name": "evelyn", "last_name": "lane"},
  {"id": "10", "first_name": "tom", "last_name": "schubert"},
  {"id": "11", "first_name": "babür", "last_name": "atakol"},
  {"id": "12", "first_name": "leif", "last_name": "geßner"},
  {"id": "13", "first_name": "cosima", "last_name": "ley"},
  {"id": "14", "first_name": "çetin", "last_name": "adan"},
  {"id": "15", "first_name": "ava", "last_name": "lam"},
  {"id": "16", "first_name": "liva", "last_name": "hansen"},
  {"id": "17", "first_name": "storm", "last_name": "larsen"},
  {"id": "18", "first_name": "inaya", "last_name": "fabre"},
  {"id": "19", "first_name": "marlen", "last_name": "laurent"},
  {"id": "20", "first_name": "nanna", "last_name": "poulsen"}
];

class ContactsDataSource extends AdvancedDataTableSource<Map<String, String>> {
  final String? keyword;

  ContactsDataSource([this.keyword]);

  @override
  Future<RemoteDataSourceDetails<Map<String, String>>> getNextPage(
      NextPageRequest pageRequest) async {
    await Future.delayed(Duration(milliseconds: 500)); // fake network delay
    var filteredData =
        data.skip(pageRequest.offset).take(pageRequest.pageSize).toList();
    if (pageRequest.sortAscending == false) {
      filteredData = filteredData.reversed.toList();
    }
    if (keyword != null && keyword!.isNotEmpty) {
      filteredData = filteredData
          .where((element) => (element['first_name']!.contains(keyword!) ||
              element['last_name']!.contains(keyword!)))
          .toList();
    }
    return Future.value(
      RemoteDataSourceDetails(data.length, filteredData),
    );
  }

  @override
  DataRow? getRow(int index) {
    return DataRow(cells: [
      DataCell(Text(lastDetails!.rows[index]["id"]!)),
      DataCell(Text(lastDetails!.rows[index]["first_name"]!)),
      DataCell(Text(lastDetails!.rows[index]["last_name"]!)),
    ]);
  }

  @override
  int get selectedRowCount => 0;
}

class MyApp extends StatefulWidget {
  MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late ContactsDataSource source;
  late TextEditingController _searchController;

  @override
  void initState() {
    this.source = ContactsDataSource();
    _searchController = TextEditingController();
    super.initState();
  }

  @override
  void dispose() {
    this._searchController.dispose();
    super.dispose();
  }

  bool _sordIdAsc = true;

  _search() {
    final keyword = this._searchController.text;
    setState(() {
      this.source = ContactsDataSource(keyword);
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          children: [
            Padding(
              padding: const EdgeInsets.all(22.0),
              child: TextField(
                onEditingComplete: _search,
                controller: _searchController,
                decoration: InputDecoration(
                  hintText: 'Press enter or tap seach button to execte search',
                  labelText: "Search",
                  suffixIcon: IconButton(
                    icon: Icon(Icons.search),
                    onPressed: _search,
                  ),
                ),
              ),
            ),
            Expanded(
              child: SingleChildScrollView(
                child: AdvancedPaginatedDataTable(
                  sortColumnIndex: 0,
                  sortAscending: _sordIdAsc,
                  addEmptyRows: false,
                  columns: [
                    DataColumn(
                      label: Text("id"),
                      onSort: (columnIndex, ascending) => setState(() {
                        _sordIdAsc = ascending;
                      }),
                    ),
                    DataColumn(label: Text("first_name")),
                    DataColumn(label: Text("last_name")),
                  ],
                  source: source,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
`

**Comment by Dev-Owl** [comment]
Below is your example with working filters. Please note, you will need to add the following to your yaml (as this version is not yet live on pub dev):
```yaml
  advanced_datatable:
    git:
      url: git://github.com/Dev-Owl/advanced_datatable.git
```


```dart
import 'package:advanced_datatable/advancedDataTableSource.dart';
import 'package:advanced_datatable/datatable.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

const data = [
  {"id": "1", "first_name": "britney", "last_name": "sims"},
  {"id": "2", "first_name": "imogen", "last_name": "edwards"},
  {"id": "3", "first_name": "lillian", "last_name": "simmmons"},
  {"id": "4", "first_name": "jessica", "last_name": "torres"},
  {"id": "5", "first_name": "noelia", "last_name": "suarez"},
  {"id": "6", "first_name": "susanna", "last_name": "mast"},
  {"id": "7", "first_name": "christa", "last_name": "lehmann"},
  {"id": "8", "first_name": "سورنا", "last_name": "رضایی"},
  {"id": "9", "first_name": "evelyn", "last_name": "lane"},
  {"id": "10", "first_name": "tom", "last_name": "schubert"},
  {"id": "11", "first_name": "babür", "last_name": "atakol"},
  {"id": "12", "first_name": "leif", "last_name": "geßner"},
  {"id": "13", "first_name": "cosima", "last_name": "ley"},
  {"id": "14", "first_name": "çetin", "last_name": "adan"},
  {"id": "15", "first_name": "ava", "last_name": "lam"},
  {"id": "16", "first_name": "liva", "last_name": "hansen"},
  {"id": "17", "first_name": "storm", "last_name": "larsen"},
  {"id": "18", "first_name": "inaya", "last_name": "fabre"},
  {"id": "19", "first_name": "marlen", "last_name": "laurent"},
  {"id": "20", "first_name": "nanna", "last_name": "poulsen"}
];

class ContactsDataSource extends AdvancedDataTableSource<Map<String, String>> {
  String? _keyword;

  set keyword(String? value) {
    _keyword = value;
    forceRemoteReload = true;
    notifyListeners();
  }

  ContactsDataSource();

  @override
  Future<RemoteDataSourceDetails<Map<String, String>>> getNextPage(
      NextPageRequest pageRequest) async {
    await Future.delayed(Duration(milliseconds: 500)); // fake network delay
    var filteredData = data;
    //-----This should happen server side--------
    //First filter
    if (_keyword != null && _keyword!.isNotEmpty)
      filteredData = filteredData
          .where((element) => (element['first_name']!.contains(_keyword!) ||
              element['last_name']!.contains(_keyword!)))
          .toList();
    //Second sort
    if (pageRequest.sortAscending == false) {
      filteredData = filteredData.reversed.toList();
    }
    //Your server needs to return the new total length, your filter is creating a new data set in the end
    final filteredTotalLength = filteredData.length;
    //Pageinate the data
    filteredData = filteredData
        .skip(pageRequest.offset)
        .take(pageRequest.pageSize)
        .toList();
    //------------------------------------------
    return Future.value(
      RemoteDataSourceDetails(filteredTotalLength, filteredData),
    );
  }

  @override
  DataRow? getRow(int index) {
    return DataRow(cells: [
      DataCell(Text(lastDetails!.rows[index]["id"]!)),
      DataCell(Text(lastDetails!.rows[index]["first_name"]!)),
      DataCell(Text(lastDetails!.rows[index]["last_name"]!)),
    ]);
  }

  @override
  int get selectedRowCount => 0;
}

class MyApp extends StatefulWidget {
  MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late ContactsDataSource source;
  late TextEditingController _searchController;

  @override
  void initState() {
    this.source = ContactsDataSource();
    _searchController = TextEditingController();
    super.initState();
  }

  @override
  void dispose() {
    this._searchController.dispose();
    super.dispose();
  }

  bool _sordIdAsc = true;

  _search() {
    setState(() {
      source.keyword = this._searchController.text;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          children: [
            Padding(
              padding: const EdgeInsets.all(22.0),
              child: TextField(
                onEditingComplete: _search,
                controller: _searchController,
                decoration: InputDecoration(
                  hintText: 'Press enter or tap seach button to execte search',
                  labelText: "Search",
                  suffixIcon: IconButton(
                    icon: Icon(Icons.search),
                    onPressed: _search,
                  ),
                ),
              ),
            ),
            Expanded(
              child: SingleChildScrollView(
                child: AdvancedPaginatedDataTable(
                  sortColumnIndex: 0,
                  sortAscending: _sordIdAsc,
                  addEmptyRows: false,
                  columns: [
                    DataColumn(
                      label: Text("id"),
                      onSort: (columnIndex, ascending) => setState(() {
                        _sordIdAsc = ascending;
                      }),
                    ),
                    DataColumn(label: Text("first_name")),
                    DataColumn(label: Text("last_name")),
                  ],
                  source: source,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

Of course, the actual filter,sort and page process has to run on the server side. Keep in mind that when you filter the data, the total number of rows is no longer all rows, it's all filtered rows (see my comments in your code above). 
I will work on this to allow you to later show something like this:

1-10 of 100 (from 1000) rows 

That would make it easier for the user to understand that the filter is active.

**Comment by Dev-Owl** [comment]
Added a feature request for this, see #2

**Comment by ahmedNY** [comment]
Thanks @Dev-Owl

**Comment by ahmedNY** [comment]
Need more enhancement,
I had this scenario
1. User entered some keyword and make search,
2. search result had 15 rows showed on (2 pages) (10 rows per page)
3. User navigated to the 2nd page
4. User make new Search. yielded 5 rows 

Expected behavior:
- data table should automatically jump to 1st page
Current behavior:
- data table show page 2, and user must click on page 1 in order to see the result

**Comment by Dev-Owl** [comment]
I agree, if the filter changes it should go back to page one. I will have to check how I can implement this proper, the control needs to be as dynamic as possible to ensure it covers all use cases.

A solution would be to create a function that allows to configure the next reload (page, page size, sorting etc.) Will look into this as soon as I have a moment, thanks for the feedback

**Comment by Dev-Owl** [comment]
I will push an update to pub.dev in the next minutes, it will contain support for your use case. 
See the online [example code](https://github.com/Dev-Owl/advanced_datatable/blob/5c8800a1b90d681cee9a30778092818c19b98a75/example/lib/main.dart#L171) and the [example page](https://dev-owl.github.io/advanced_datatable/#/).
