### ISSUE TITLE
Improve default loading behavior

### ISSUE THREAD

**Issue by Dev-Owl** [Dev-Owl/advanced_datatable#14]
**Is your feature request related to a problem? Please describe.**
The current default loader might draw the spinner outside the visible area (below or above) if you have selected enough rows by page to exceed the available space.

**Describe the solution you'd like**
Draw the spinner in the center of the screen, regardless of how many rows are selected, not in the relative center of the widget.

**Comment by yousseffarag96** [comment]
i think you need to close this issue

**Comment by Dev-Owl** [comment]
Yes you are correct, thanks for pointing that out 👍
