### ISSUE TITLE
Fix First & last button on default pagination when use RTL Localization

### ISSUE THREAD

**Issue by anasasra** [Dev-Owl/advanced_datatable#15]
The default pagination in this plug (advanced_datatable) is NOT support by default RTL localizations,
my application is in Hebrew language (right to left language) and I think the buttons to go to first & last  page are NOT build correctly.

![Screenshot from 2021-11-23 17-06-10](https://user-images.githubusercontent.com/74556287/143051388-9dc49f92-ae0c-41d5-a61e-e14ca6e715ad.png)

**Comment by Dev-Owl** [comment]
I need to loom into this, the foot is still based to a big part of the original Flutter footer. Does the normal datatable support this correctly? 

Also to make sure I got you right, can you show in a screenshot what you would expect?

**Comment by yousseffarag96** [comment]
this issue is done
