### ISSUE TITLE
Is there any way to set the alignment of the pagination without build custom footer.

### ISSUE THREAD

**Issue by anasasra** [Dev-Owl/advanced_datatable#16]
Please provide as many information as possible to answer your question.
Is there any way to centralizer or change alignment to left/right without building custom footer ?!

**Comment by Dev-Owl** [comment]
Not yet, feel free to adjust and create a push request:
https://github.com/Dev-Owl/advanced_datatable/blob/98032512c5736fcae3e4b97e7d23a88ad54370fe/lib/datatable.dart#L742

The row would need an alignment property to center the elements. That could come from the widget with a default to not break the current flow.

**Comment by anasasra** [comment]
Ok I will do it tomorrow, what you think should be the default alignment ?

**Comment by Dev-Owl** [comment]
I would vote for the one that is set on the row by flutters default. In the
end the change should not break current pages or require people to adjust
the code to get the current behavior.

**Comment by anasasra** [comment]
> Not yet, feel free to adjust and create a push request:
> 
> https://github.com/Dev-Owl/advanced_datatable/blob/98032512c5736fcae3e4b97e7d23a88ad54370fe/lib/datatable.dart#L742
> 
> The row would need an alignment property to center the elements. That could come from the widget with a default to not break the current flow.

is there any good reason for wrapping the Row widget with SingleChildScrollView ? because i can't see any major effect.
The alignment of row will NOT work properly when wrap it with SingleChildScrollView, so I remove this widget to fix this issue.
The default behavior changed so the footer align to start (left when English) instead of end, but actually this is the default alignment of the row, you just reverse when used  SingleChildScrollView.

**Comment by Dev-Owl** [comment]
The main branch has an option to align the default footer, will be part of the next pub.dev update
