### ISSUE TITLE
Advance data table  ( getting data from Firestore to ListviewBuilder

### ISSUE THREAD

**Issue by ncincd** [Dev-Owl/advanced_datatable#20]
Pls I need your assistance how can I get data from Firestore to Advance Data table to a listviewBuilder thank you

**Comment by Dev-Owl** [comment]
The idea of this package is to feed in data from a remote source, the remote source itself can be anything. The included example shows how to deal with a REST service.

You will need to put your firebase code inside the datasource. Never used it so I can't tell you how nor do I know what you mean with the second part of your question.

**Comment by Dev-Owl** [comment]
Either resolved or no interest anymore, cleaning up. You are welcome to open the issue again
