### ISSUE TITLE
Columns width with long strings

### ISSUE THREAD

**Issue by alan-valenzuela93** [Dev-Owl/advanced_datatable#22]
Hi! I'm facing this problem when the string on a datacell it's longer than the width of a column. For example, on the normal DataTable package or PaginatedDataTable, when a string it's longer than the space available within the column, the overflowed text goes to a second line. But on this package it goes into a single line, which in some cases provokes that (depending on the width of the table) appear even a horizontal scrolling. Is there any way so that the column doesn't take the entire length of a string? Thank you

**Comment by Dev-Owl** [comment]
I would address this like below:

```dart
  DataRow getRow(
    SelectedCallBack callback,
    List<String> selectedIds,
  ) {
    return DataRow(
      cells: [
        DataCell(Text(id.toString())),
        const DataCell(
          SizedBox(
            width: 200,
            child: Text(
              "Very long text that should line break if it gets to long for the parent container",
              maxLines: 2,
              overflow: TextOverflow.ellipsis,
            ),
          ),
        ),
        DataCell(Text(firstName)),
        DataCell(Text(lastName)),
        DataCell(Text(phone)),
      ],
      onSelectChanged: (newState) {
        callback(id.toString(), newState ?? false);
      },
      selected: selectedIds.contains(id.toString()),
    );
  }
```

The result will create a data cell that has line breaks at the width of the container.
