### ISSUE TITLE
Reload from server while keeping skeleton static

### ISSUE THREAD

**Issue by zulfi007** [Dev-Owl/advanced_datatable#6]
While loading from server. Screen gets white and widget rebuild itself. Instead it would be nice to keep  table skeleton  visible and just reload the rows portion with loading indicator . In this way, it would be much more interactive

**Comment by Dev-Owl** [comment]
Hi,
You can set a custom loading widget with the loadingWidget property.

Maybe it would be a nice idea to change the default loader to the suggested be inside the table instead of replacing it. Keep the header section and have the loading inside the table.
